services:

  ai-log-analyzer:

    build: .

    container_name: ai-log-analyzer

    ports:
      - "5001:5000"

    environment:

      OLLAMA_URL: http://ollama:11434/api/generate

      OLLAMA_MODEL: qwen2.5-coder:3b

      MAX_LOG_LENGTH: 12000

      PORT: 5000

      # Jenkins
      JENKINS_URL: ${JENKINS_URL:-}
      JENKINS_USER: ${JENKINS_USER:-}
      JENKINS_TOKEN: ${JENKINS_TOKEN:-}

      # Argo CD
      ARGOCD_URL: ${ARGOCD_URL:-}
      ARGOCD_TOKEN: ${ARGOCD_TOKEN:-}

      # GitHub
      GITHUB_TOKEN: ${GITHUB_TOKEN:-}
      GITHUB_REPO: ${GITHUB_REPO:-}

      GITHUB_API_URL: https://api.github.com

    volumes:

      - /var/run/docker.sock:/var/run/docker.sock

    group_add:

      - "1001"

    depends_on:

      - ollama

    restart: unless-stopped


  ollama:

    image: ollama/ollama:latest

    container_name: ollama

    ports:

      - "11434:11434"

    volumes:

      - ollama_data:/root/.ollama

    restart: unless-stopped


volumes:

  ollama_data: